application:
  name: DevOpsSimulator
  version: 2.0.0
  environment: production   # default production, dev optional

server:
  host: 0.0.0.0
  port: 8080                # production default
  ssl_enabled: true
  hot_reload: false         # disabled by default

logging:
  level: INFO
  format: json

development:
  environment: development
  host: localhost
  port: 3000
  ssl_enabled: false
  hot_reload: true
  mock_apis: true
  debug_mode: true

