<<<<<<< HEAD
# Production Application Configuration
# Unified Application Configuration
application:
  name: DevOpsSimulator
  version: 3.0.0
  environment: production-testing
  experimental_mode: true

server:
  host: 0.0.0.0
  port: 8080
  ssl_enabled: true
  multi_port: [8080, 9000, 9001]

logging:
  level: INFO
  format: structured
  output: /var/log/devops-simulator.log
  ai_analysis: enabled

database:
  host: cluster.example.com
  port: 5432
  name: devops_unified
  distributed: true

features:
  auto_scaling: advanced
  load_balancer: ai-optimized
  backup_enabled: true
  chaos_engineering: enabled

ai_features:
  predictive_scaling: true
  anomaly_detection: true
  auto_optimization: true
  model_version: "v2.1.0"

cloud_providers:
  - aws
  - azure
  - gcp
  - digitalocean

security:
  zero_trust: enabled
  encryption: AES-256
  audit_logging: comprehensive
